package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"fmt"
	"time"

	"github.com/ave1995/practice-go/grpc-client/api/graphql/graph/model"
	"github.com/ave1995/practice-go/proto"
)

// SendMessage is the resolver for the sendMessage field.
func (r *mutationResolver) SendMessage(ctx context.Context, text string) (*model.Message, error) {
	if text == "" {
		return nil, fmt.Errorf("text cannot be empty")
	}

	req := &proto.SendMessageRequest{
		Message: &proto.Message{
			Text: text,
		},
	}

	testCtx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()

	msg, err := r.grpcConn.SendMessage(testCtx, req)
	if err != nil {
		return nil, fmt.Errorf("send message via gRPC: %w", err)
	}

	gm := &model.Message{
		ID:   msg.Id,
		Text: msg.Message,
	}

	return gm, nil
}

// Messages is the resolver for the messages field.
func (r *queryResolver) Messages(ctx context.Context) ([]*model.Message, error) {
	panic(fmt.Errorf("not implemented: Messages - messages"))
}

// Message is the resolver for the message field.
func (r *queryResolver) Message(ctx context.Context, id string) (*model.Message, error) {
	panic(fmt.Errorf("not implemented: Message - message"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
